version: '1.0'
services:
  flask-app:
    build: ./backend
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - ./db/dbdata6:/data/db